import type { Event, Project } from './types';

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Annual Tech Summit',
    date: '2024-10-25T10:00:00.000Z',
    description: 'A gathering of the brightest minds in technology.',
    category: 'Academic',
  },
  {
    id: '2',
    title: 'Career Fair 2024',
    date: '2024-11-15T09:00:00.000Z',
    description: 'Connect with top employers from various industries.',
    category: 'Career',
  },
  {
    id: '3',
    title: 'Spring Music Festival',
    date: '2025-04-12T14:00:00.000Z',
    description: 'An outdoor music event featuring local bands.',
    category: 'Social',
  },
  {
    id: '4',
    title: 'Python for Data Science Workshop',
    date: '2024-11-05T13:00:00.000Z',
    description: 'A hands-on workshop on data analysis with Python.',
    category: 'Workshop',
  },
  {
    id: '5',
    title: 'Finals Week Study Group',
    date: '2024-12-10T18:00:00.000Z',
    description: 'Collaborative study session for upcoming final exams.',
    category: 'Academic',
  },
  {
    id: '6',
    title: 'Welcome Week Mixer',
    date: '2024-09-02T17:00:00.000Z',
    description: 'Meet new students and kick off the academic year.',
    category: 'Social',
  },
   {
    id: '7',
    title: 'Robotics Club Info Session',
    date: '2024-09-02T11:00:00.000Z',
    description: 'Learn about the robotics club and upcoming projects.',
    category: 'Academic',
  },
];

export const mockProjects: Project[] = [
  {
    id: 'p1',
    title: 'AI-Powered Art Generator',
    student: 'Jane Doe',
    year: 2024,
    category: 'Technology',
    description: 'A deep learning model that generates unique artworks based on text prompts.',
    imageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: 'p2',
    title: 'Interactive Sculpture Exhibit',
    student: 'John Smith',
    year: 2023,
    category: 'Art',
    description: 'An art installation that responds to visitor movement and sound.',
    imageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: 'p3',
    title: 'Sustainable Urban Farming Model',
    student: 'Emily White',
    year: 2024,
    category: 'Science',
    description: 'A research project on creating efficient vertical farming systems for cities.',
    imageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: 'p4',
    title: 'Campus Thrift-Shop App',
    student: 'Michael Brown',
    year: 2022,
    category: 'Business',
    description: 'A mobile app for students to buy and sell used goods on campus.',
    imageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: 'p5',
    title: 'VR Campus Tour',
    student: 'Sarah Green',
    year: 2023,
    category: 'Technology',
    description: 'A virtual reality experience for prospective students to tour the campus.',
    imageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: 'p6',
    title: 'Bioplastic from Algae',
    student: 'David Lee',
    year: 2024,
    category: 'Science',
    description: 'Developing a biodegradable plastic alternative using marine algae.',
    imageUrl: 'https://placehold.co/600x400.png',
  },
];
